#!/bin/bash

# Author	: Ramkrushna Bolewar
# script Name	: Cows and Bulls Game

:<< COMMENTED
############################################################################# 
2 # 
3 '''Create a program that will play the “cows and bulls” game with the user. The game works like this: 
4  
5 Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end. 
6  
7 Say the number generated by the computer is 1038. An example interaction could look like this: 
8  
9   Welcome to the Cows and Bulls Game!  
10   Enter a number:  
11   >>> 1234 
12   2 cows, 0 bulls 
13   >>> 1256 
14   1 cow, 1 bull 
15   ... 
16  
17 Until the user guesses the number. 
18 ''' 
#################################################################################
COMMENTED

##### variables #####
num2guess=$(( RANDOM % (9999 - 1000 + 1) + 1000 )); 
first_bit=$(( $num2guess / 1000 )); 
second_bit=$(( ($num2guess / 100) % 10  )); 
third_bit=$(( ($num2guess / 10) % 10 )); 
fourth_bit=$(( $num2guess % 10 ));

#echo $num2guess $first_bit $second_bit $third_bit $fourth_bit

##### functions #####
count_cowsNbulls() {
	count_cows=0; #counter for cows
	count_bulls=0; #counter for bulls
	
	temp_var=$(( $userGuess / 1000 ));
	if [ $2 -eq  $temp_var ];then
		count_cows=$(( $count_cows + 1 ));
	elif [ $3 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	elif [ $4 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	elif [ $5 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	fi

	temp_var=$(( ($userGuess / 100) % 10 ));
	if [ $3 -eq $temp_var ];then
		count_cows=$(( $count_cows + 1 ));
	elif [ $2 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	elif [ $4 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	elif [ $5 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	fi

	temp_var=$(( ($userGuess / 10) % 10 ));
	if [ $4 -eq $temp_var ];then
		count_cows=$(( $count_cows + 1 ));
	elif [ $2 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	elif [ $3 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	elif [ $5 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	fi

	temp_var=$(( $userGuess % 10 ));
	if [ $5 -eq $temp_var ];then
		count_cows=$(( $count_cows + 1 ));
	elif [ $2 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	elif [ $3 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	elif [ $4 -eq $temp_var ];then
		count_bulls=$(( $count_bulls + 1 ));
	fi	
	
	echo " cows  : $count_cows ";
	echo " bulls : $count_bulls ";
}

while true
do
	read -p "Enter the number between 1000-9999 (0000 to exit): " userGuess
	if [ $userGuess -eq 0000 ];then
		exit;
        elif [[ ($userGuess -ge 1000) && ($userGuess -le 9999) ]];then
		if [ $userGuess -eq $num2guess ];then
                	echo -e "\nYour guess is RIGHT and I declared you as BATMAN : GO ENJOY"
                	exit;
       		else
                	count_cowsNbulls $userGuess $first_bit $second_bit $third_bit $fourth_bit;
        	fi
	else
		echo ">> Please enter the number between 1000 and 9999 <<"
		continue;
        fi
done
