--This script grants mention permission to user all tables

DECLARE
CURSOR C1 IS SELECT OWNER, TABLE_NAME FROM ALL_TABLES WHERE OWNER LIKE "<TABLE_OWNER>";
COMMAND VARCHAR(200);
BEGIN
	FOR C IN C1 LOOP
		COMMAND :='GRANT SELECT, INSERT, UPDATE, DELETE ON '||C.OWNER||'.'||C.TABLE_NAME||' TO <USERNAME>';
		EXECUTE IMMEDIATE COMMAND;
	END LOOP;
END;
